/* etesca::codegen --input <spec> --output <file.cpp>

MUST stay dependency-free: cross-platform builds import this from the host
build tree */

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

namespace {

[[nodiscard]] std::string_view trim(std::string_view text) noexcept {
    constexpr std::string_view whitespace{" \t\r\n"};

    const size_t first = text.find_first_not_of(whitespace);
    if (first == std::string_view::npos) {
        return {};
    }

    const size_t last = text.find_last_not_of(whitespace);
    return text.substr(first, last - first + 1);
}

void usage(std::ostream& stream) {
    stream << "usage: etesca_codegen --input <spec> --output <file.cpp>\n";
}

} // namespace

int main(int argc, char** argv) {
    std::string input;
    std::string output;

    for (int i = 1; i < argc; ++i) {
        const std::string_view arg{argv[i]};
        const bool has_value = (i + 1) < argc;

        if (arg == "--input" && has_value) {
            input = argv[++i];
        } else if (arg == "--output" && has_value) {
            output = argv[++i];
        } else if (arg == "--help") {
            usage(std::cout);
            return EXIT_SUCCESS;
        } else {
            std::cerr << "etesca_codegen: unexpected argument '" << arg << "'\n";
            usage(std::cerr);
            return EXIT_FAILURE;
        }
    }

    if (input.empty() || output.empty()) {
        usage(std::cerr);
        return EXIT_FAILURE;
    }

    std::ifstream in{input};
    if (!in) {
        std::cerr << "etesca_codegen: cannot open input '" << input << "'\n";
        return EXIT_FAILURE;
    }

    std::vector<std::string> entries;
    for (std::string line; std::getline(in, line);) {
        const std::string_view entry = trim(line);
        if (entry.empty() || entry.front() == '#') {
            continue;
        }
        entries.emplace_back(entry);
    }

    std::ofstream out{output};
    if (!out) {
        std::cerr << "etesca_codegen: cannot open output '" << output << "'\n";
        return EXIT_FAILURE;
    }

    out << "// Generated by etesca::codegen from \"" << input << "\". Do not edit.\n"
        << "\n"
        << "#include <cstddef>\n"
        << "\n"
        << "namespace etesca::detail {\n"
        << "\n"
        << "extern const char* const kLevelTable[];\n"
        << "extern const std::size_t kLevelTableSize;\n"
        << "\n"
        << "// nullptr-terminated: a zero-sized array is ill-formed.\n"
        << "const char* const kLevelTable[] = {\n";

    for (const std::string& entry : entries) {
        out << "\t\"" << entry << "\",\n";
    }

    out << "\tnullptr,\n"
        << "};\n"
        << "\n"
        << "const std::size_t kLevelTableSize = " << entries.size() << "U;\n"
        << "\n"
        << "} // namespace etesca::detail\n";

    if (!out) {
        std::cerr << "etesca_codegen: failed writing '" << output << "'\n";
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
